# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- develop

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        defaultContext: false
        context: '$(System.DefaultWorkingDirectory)'
        command: build
        dockerfile: '$(System.DefaultWorkingDirectory)/DeadFishStudio.Product.Application.Api/Dockerfile'
        tags: |
          $(tag)