version: '3.4'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Alaska2017"
      ACCEPT_EULA: "Y"
    ports:
      - "5433:1433"

  deadfishstudio.infnetdevops.presentation:
    image: luca16s/devops_marketlist_presentation
    environment:
      - ProductUrl=http://10.0.75.1:65400/
      - MarketListUrl=http://10.0.75.1:53452/
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "53937:80"
    depends_on:
      - marketlist.api
      - product.api

  marketlist.api:
    image: luca16s/devops_marketlist_api
    environment:
      - ConnectionString=mssql;Database=MarketListDb;User Id=sa;Password=Alaska2017'
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    expose:
      - "80"
    ports:
      - "53452:80"
    depends_on:
      - mssql

  product.api:
    image: luca16s/devops_product_api
    environment:
      - ConnectionString=Server=mssql;Database=ProductDb;User Id=sa;Password=Alaska2017
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    expose:
      - "80"
    ports:
      - "65400:80"
    depends_on:
      - mssql