version: '3.4'

services:
  mssql:
    image: "microsoft/mssql-server-linux:latest"
    environment:
      SA_PASSWORD: "Alaska2017"
      ACCEPT_EULA: "Y"
    ports:
      - "5433:1433"

  deadfishstudio.infnetdevops.presentation:
    image: ${DOCKER_REGISTRY-}devops_marketlist_presentation
    build:
      context: .
      dockerfile: DeadFishStudio.InfnetDevOps.Presentation/Dockerfile
    environment:
      - ProductUrl=http://10.0.75.1:65400/
      - MarketListUrl=http://10.0.75.1:53452/
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "53937:80"
    depends_on:
      - marketlist.api
      - product.api

  marketlist.api:
    image: ${DOCKER_REGISTRY-}devops_marketlist_api
    build:
      context: .
      dockerfile: DeadFishStudio.MarketList.Application.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    expose:
      - "80"
    ports:
      - "53452:80"
    depends_on:
      - mssql

  product.api:
    image: ${DOCKER_REGISTRY-}devops_product_api
    build:
      context: .
      dockerfile: DeadFishStudio.Product.Application.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    expose:
      - "80"
    ports:
      - "65400:80"
    depends_on:
      - mssql