version: '3.4'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Alaska2017"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: sqlcmd -S devopsnetwork -U SA -P 'Alaska2017' -Q 'select distinct 1 from master'
    ports:
      - "5433:1433"

  deadfishstudio.infnetdevops.presentation:
    image: luca16s/devops_marketlist_presentation
    build:
      context: .
      dockerfile: DeadFishStudio.InfnetDevOps.Presentation/Dockerfile
    depends_on:
      - deadfishstudio.marketlist.application.api
      - deadfishstudio.product.application.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44396
    ports:
      - "53937:80"
      - "44396:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  deadfishstudio.marketlist.application.api:
    image: luca16s/devops_marketlist_api
    build:
      context: .
      dockerfile: DeadFishStudio.MarketList.Application.Api/Dockerfile
    depends_on:
      - mssql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44361
    ports:
      - "53452:80"
      - "44361:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  deadfishstudio.product.application.api:
    image: luca16s/devops_product_api
    build:
      context: .
      dockerfile: DeadFishStudio.Product.Application.Api/Dockerfile
    depends_on:
      - mssql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44301
    ports:
      - "65400:80"
      - "44301:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro