// <auto-generated />
using System;
using DeadFishStudio.MarketList.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace DeadFishStudio.MarketList.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MarketListContext))]
    partial class MarketListContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("deadfish")
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DeadFishStudio.MarketList.Domain.Model.Entities.MarketList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MKLT_SQ_MARKET_LIST");

                    b.Property<DateTime>("DataDeCriacao")
                        .HasColumnName("MKLT_DT_CREATION");

                    b.Property<DateTime>("DataDeModificacao")
                        .HasColumnName("MKLT_DT_MODIFICATION");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("MKLT_NM_MARKET_LIST");

                    b.HasKey("Id");

                    b.ToTable("MARKETLIST");
                });

            modelBuilder.Entity("DeadFishStudio.MarketList.Domain.Model.MarketListProduct", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MKLT_SQ_PRODUCT");

                    b.Property<Guid>("MKLT_SQ_MARKET_LIST");

                    b.HasKey("ProductId");

                    b.ToTable("ITEMS");
                });
#pragma warning restore 612, 618
        }
    }
}
